### ISSUE TITLE
check_tree: Key Lookup Error in Iterator to build path

### ISSUE THREAD

**Issue by fbennets** [open-decision/Prototype#38]
**Describe the bug**

**To Reproduce**

1. Reference a node in the logic field of another one
2. Delete the referenced node
3. Click "Export tree"
4. Key Lookup error, as the build path fct will do a key-lookup with the ID of the deleted node

**Expected behavior**
The error should be logged and displayed to the user afterward.

**Additional context**
 Possible solution: catch the error using try/except, verify the source of the error and display it in the check_tree view.

**Comment by aaronrothmann** [comment]
no more bug fixes for prototype
