### ISSUE TITLE
Build human-readable representation and wiki for decision-trees

### ISSUE THREAD

**Issue by fbennets** [open-decision/Prototype#54]
**Is your feature request related to a problem? Please describe.**
We should enhance the options of sharing and collaborating for decision trees so that several individuals and groups can develop trees together, share/discuss them afterwards and make use of the knowledge encoded in the trees.

**Describe the solution you'd like**
We should have:
- a human-readable representation of the trees to enable discussion and collaboration in an easy way
- a wiki, where the trees can be discussed and improved to ensure long-time preservation
- the option, to create decision trees with several collaborators in the builder

**Additional context**
This should be a feature for release 0.2

**Comment by aaronrothmann** [comment]
transferred to new builder
